# Lab 14 Simple Linear Regression: The relationship between salary and experience 


In [14]:
# Import libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

import plotly.express as px 
import plotly.graph_objs as go 
from plotly.offline import iplot

In [15]:
df = pd.read_csv(r'D:\Python Learning\Python-Personal-Exercises\Lab 14 Simple Linear Regression (Experience and Salary)\Salary_Data.csv')
df.head().style.background_gradient(cmap='pink_r')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [17]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [18]:
df.isnull().sum().sum()

0

In [19]:
df.describe().style.background_gradient(cmap='pink_r')

In [22]:
iplot(go.Figure([go.Scatter(x=df.YearsExperience,y=df.Salary,mode='markers')]))


In [28]:
# Assigning values to X and Y
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values
# Split dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42) # dataset has 30 observations and test_size is taken as 33% of the total observation. T

In [29]:
print(X_train)
print(X_test)

[[ 2.2]
 [ 5.1]
 [ 2.9]
 [ 4.1]
 [ 4. ]
 [ 7.9]
 [ 1.3]
 [ 1.5]
 [ 9. ]
 [ 2. ]
 [ 7.1]
 [ 9.5]
 [ 5.9]
 [10.5]
 [ 6.8]
 [ 3.2]
 [ 3.9]
 [ 4.5]
 [ 6. ]
 [ 3. ]]
[[ 9.6]
 [ 4.9]
 [ 8.2]
 [ 5.3]
 [ 3.2]
 [ 3.7]
 [10.3]
 [ 8.7]
 [ 4. ]
 [ 1.1]]


In [30]:
print(Y_train)
print(Y_test)

[ 39891.  66029.  56642.  57081.  55794. 101302.  46205.  37731. 105582.
  43525.  98273. 116969.  81363. 121872.  91738.  54445.  63218.  61111.
  93940.  60150.]
[112635.  67938. 113812.  83088.  64445.  57189. 122391. 109431.  56957.
  39343.]


In [31]:
# Linear regression 
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [34]:
Y_pred = model.predict(X_test)
x_range = np.linspace(X.min(), X.max(), 100)
y_range = model.predict(x_range.reshape(-1, 1))

fig = go.Figure([
        go.Scatter(x=X_train.squeeze(), y=Y_train, 
                   name='train', mode='markers'),
        go.Scatter(x=X_test.squeeze(), y=Y_test, 
                   name='test', mode='markers'),
        go.Scatter(x=x_range, y=y_range, 
                   name='prediction')
    ])

fig.show()

In [36]:
coe = model.coef_
coe

array([9426.03876907])

In [38]:
int = model.intercept_
int

25324.33537924433

In [40]:
# Predicting 
print(model.predict([[11]]))

[129010.76183907]


In [41]:
# model evaluation 
from sklearn import metrics
print('Mean Squared Error (MSE)  : ', metrics.mean_squared_error(Y_test, Y_pred))

Mean Squared Error (MSE)  :  35301898.887134895


In [43]:
import statsmodels.api as sm 
X_stat=sm.add_constant(X_train)
regsummary=sm.OLS(Y_train,X_stat).fit()
regsummary.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.955
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     381.3
Date:                Thu, 03 Nov 2022   Prob (F-statistic):           1.45e-13
Time:                        22:04:51   Log-Likelihood:                -200.48
No. Observations:                  20   AIC:                             405.0
Df Residuals:                      18   BIC:                             406.9
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.532e+04   2743.538      9.231      0.000    1.96e+04    3.11e+04
x1          9426.0388    482.706     19.527      0.000    8411.911    1.04e+04
==============================================================================
Omnibus:                        0.822   Durbin-Watson:                   1.772
Prob(Omnibus):                  0.663   Jarque-Bera (JB):                0.819
Skew:                           0.380   Prob(JB):                        0.664
Kurtosis:                       2.363   Cond. No.                         12.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [44]:
print("Adjusted R-Square : ",regsummary.rsquared_adj)
print("R-Square : ",regsummary.rsquared)

Adjusted R-Square :  0.9524194554302405
R-Square :  0.9549236946181227
